export const INCOME_SETTINGS_STRINGS = {
  screenTitle: 'Additional Income',
  sectionTitle: 'This Month',
  emptyTitle: 'No income entries yet',
  emptyBody: 'Add extra income like bonuses, freelance work, or cashback.',
  addButton: 'Add Income',
  editButton: 'Edit',
  deleteButton: 'Delete',
  cancelButton: 'Cancel',
  saveButton: 'Save',
  form: {
    addTitle: 'Add Income',
    editTitle: 'Edit Income',
    amountLabel: 'Amount',
    amountPlaceholder: 'e.g. 5000',
    typeLabel: 'Type',
    typePlaceholder: 'Select type',
    customTypeLabel: 'Custom Type',
    customTypePlaceholder: 'e.g. Side hustle',
    descriptionLabel: 'Description (optional)',
    descriptionPlaceholder: 'e.g. Freelance project',
    dateLabel: 'Date',
  },
  deleteAlert: {
    title: 'Delete Income Entry?',
    body: 'This will permanently remove this income entry.',
    cancel: 'Cancel',
    confirm: 'Delete',
  },
  validation: {
    amountRequired: 'Amount must be greater than 0',
    typeRequired: 'Please select a type',
    customTypeRequired: 'Please enter a custom type',
  },
  logs: {
    createFailed: 'Failed to create income entry:',
    updateFailed: 'Failed to update income entry:',
    deleteFailed: 'Failed to delete income entry:',
  },
  alerts: {
    createFailed: 'Failed to add income. Please try again.',
    updateFailed: 'Failed to update income. Please try again.',
    deleteFailed: 'Failed to delete income. Please try again.',
    errorTitle: 'Error',
  },
  budget: {
    additionalIncomeLabel: 'Additional Income',
    additionalIncomeBadge: (amount: string) => `+${amount} this month`,
  },
} as const;
