export const INCOME_FORM_STRINGS = {
  modalTitle: 'Log Income',
  currencySymbol: '₹',
  amountLabel: 'Amount',
  amountPlaceholder: 'e.g. 5000',
  typeLabel: 'Type',
  typePlaceholder: 'Select type',
  typeModalTitle: 'Select Income Type',
  customTypeLabel: 'Custom Type',
  customTypePlaceholder: 'e.g. Side hustle',
  descriptionLabel: 'Description (optional)',
  descriptionPlaceholder: 'e.g. Freelance project',
  dateLabel: 'Date',
  datePlaceholder: 'YYYY-MM-DD',
  submitButton: 'Log Income',
  validation: {
    amountRequired: 'Amount must be greater than 0',
    typeRequired: 'Please select a type',
    customTypeRequired: 'Please enter a custom type',
  },
  alerts: {
    createFailed: 'Failed to log income. Please try again.',
    errorTitle: 'Error',
  },
  logs: {
    createFailed: 'Failed to create income entry:',
  },
} as const;

export const ALL_INCOME_STRINGS = {
  screenTitle: 'All Income',
  noIncome: 'No income entries this month',
  loadErrorTitle: 'Could not load income',
  loadErrorBody: 'Something went wrong. Tap retry to try again.',
  retryButton: 'Retry',
} as const;

export const INCOME_DETAIL_STRINGS = {
  screenTitle: 'Income Detail',
  loadingLabel: 'Loading...',
  notFoundLabel: 'Income entry not found',
  amountLabel: 'Amount',
  typeLabel: 'Type',
  descriptionLabel: 'Description',
  dateLabel: 'Date',
  noDescriptionFallback: 'No description',
  editButton: 'Edit',
  deleteButton: 'Delete',
  saveChangesButton: 'Save Changes',
  cancelButton: 'Cancel',
  deleteAlertTitle: 'Delete Income Entry?',
  deleteAlertBody: 'This will permanently remove this income entry.',
  deleteAlertCancel: 'Cancel',
  deleteAlertConfirm: 'Delete',
  changesSavedToast: 'Changes saved',
  saveChangesFailedToast: 'Failed to save changes. Please try again.',
  deleteFailedToast: 'Failed to delete. Please try again.',
  descriptionPlaceholder: 'e.g. Freelance project',
  amountPlaceholder: 'e.g. 5000',
  currencySymbol: '₹',
  typeModalTitle: 'Select Income Type',
  customTypeLabel: 'Custom Type',
  customTypePlaceholder: 'e.g. Side hustle',
  validation: {
    amountRequired: 'Amount must be greater than 0',
    amountPositive: 'Amount must be a positive number',
    typeRequired: 'Please select a type',
    customTypeRequired: 'Please enter a custom type',
    dateRequired: 'Date is required',
    dateValidISO: 'Date must be in YYYY-MM-DD format',
  },
} as const;

export const INCOME_SETTINGS_STRINGS = {
  screenTitle: 'Additional Income',
  sectionTitle: 'This Month',
  emptyTitle: 'No income entries yet',
  emptyBody: 'Add extra income like bonuses, freelance work, or cashback.',
  addButton: 'Add Income',
  editButton: 'Edit',
  deleteButton: 'Delete',
  cancelButton: 'Cancel',
  saveButton: 'Save',
  form: {
    addTitle: 'Add Income',
    editTitle: 'Edit Income',
    amountLabel: 'Amount',
    amountPlaceholder: 'e.g. 5000',
    typeLabel: 'Type',
    typePlaceholder: 'Select type',
    customTypeLabel: 'Custom Type',
    customTypePlaceholder: 'e.g. Side hustle',
    descriptionLabel: 'Description (optional)',
    descriptionPlaceholder: 'e.g. Freelance project',
    dateLabel: 'Date',
  },
  deleteAlert: {
    title: 'Delete Income Entry?',
    body: 'This will permanently remove this income entry.',
    cancel: 'Cancel',
    confirm: 'Delete',
  },
  validation: {
    amountRequired: 'Amount must be greater than 0',
    typeRequired: 'Please select a type',
    customTypeRequired: 'Please enter a custom type',
  },
  logs: {
    createFailed: 'Failed to create income entry:',
    updateFailed: 'Failed to update income entry:',
    deleteFailed: 'Failed to delete income entry:',
  },
  alerts: {
    createFailed: 'Failed to add income. Please try again.',
    updateFailed: 'Failed to update income. Please try again.',
    deleteFailed: 'Failed to delete income. Please try again.',
    errorTitle: 'Error',
  },
  budget: {
    additionalIncomeLabel: 'Additional Income',
    additionalIncomeBadge: (amount: string) => `+${amount} this month`,
  },
} as const;
