export const SETTINGS_COMMON_STRINGS = {
  errorAlertTitle: 'Error',
  saveChangesFailed: 'Failed to save changes. Please try again.',
  saveChangesButton: 'Save Changes',
  itemsSuffix: 'items',
} as const;

export const SETTINGS_SCREEN_STRINGS = {
  title: 'Settings',
  appearanceTitle: 'Appearance',
  financialDataTitle: 'Financial Data',
  budgetOverviewTitle: 'Budget Overview',
  editProfileButton: 'Edit Profile',
  userFallback: 'User',
  perMonthSuffix: '/month',
} as const;

export const EDIT_PROFILE_STRINGS = {
  screenTitle: 'Edit Profile',
  saveFailedLog: 'Failed to save profile:',
  saveFailedAlert: 'Failed to save profile. Please try again.',
  saveButton: 'Save Changes',
  heading: 'Update Your Profile',
  subheading: 'Make changes to your profile information',
  deleteAccountButton: 'Delete Account',
  deleteAccountTitle: 'Delete Account?',
  deleteAccountBody: 'This will permanently delete all your data. This action cannot be undone.',
  cancelButton: 'Cancel',
  deleteButton: 'Delete',
  postDeleteRedirect: '/onboarding/welcome',
} as const;

export const DEBTS_SETTINGS_STRINGS = {
  screenTitle: 'Debts & Loans',
  emiLabel: 'EMI',
  secondaryAmountLabel: 'EMI',
  createFailedLog: 'Failed to create debt:',
  updateFailedLog: 'Failed to update debt:',
  removeFailedLog: 'Failed to remove debt:',
} as const;

export const FIXED_EXPENSES_SETTINGS_STRINGS = {
  screenTitle: 'Fixed Expenses',
  createFailedLog: 'Failed to create fixed expense:',
  updateFailedLog: 'Failed to update fixed expense:',
  removeFailedLog: 'Failed to remove fixed expense:',
} as const;

export const SAVINGS_SETTINGS_STRINGS = {
  screenTitle: 'Savings Goals',
  createFailedLog: 'Failed to create savings goal:',
  updateFailedLog: 'Failed to update savings goal:',
  removeFailedLog: 'Failed to remove savings goal:',
} as const;

export const CREDIT_CARDS_SETTINGS_STRINGS = {
  screenTitle: 'Credit Cards',
  manageCardsLabel: 'Manage Cards',
  cardsLinkedSuffix: 'cards linked',
  addCardButton: 'Add Card',
  editCardButton: 'Edit',
  deleteCardButton: 'Delete',
  payBillButton: 'Pay Bill',
  emptyTitle: 'No credit cards yet',
  emptyBody: 'Add a card to track spending and due dates.',
  loadingLabel: 'Loading credit cards...',
  dueLabel: 'Due',
  usedLabel: 'used',
  ofLabel: 'of',
  limitLabel: 'Limit',
  utilizationLabel: 'used',
  listStep: {
    heading: 'Credit Cards',
    subheading: 'Add your cards to track spending and due dates',
    addButton: 'Add Credit Card',
    continueButton: 'Continue',
    skipButton: 'Skip',
    form: {
      addButton: 'Add Card',
      cancelButton: 'Cancel',
      saveButton: 'Save Card',
      cancelEditButton: 'Cancel',
    },
  },
  listItem: {
    separator: ' • ',
    archivedSuffix: '· Archived',
  },
  archivedSection: {
    title: 'Archived',
    unarchiveButton: 'Unarchive',
    unarchiveAlertTitle: 'Reactivate Card?',
    unarchiveAlertBody: 'Your transaction history will stay intact. The balance will start from zero.',
    unarchiveConfirm: 'Reactivate',
    unarchiveCancel: 'Cancel',
    unarchiveFailed: 'Failed to unarchive credit card:',
  },
  alerts: {
    deleteTitle: 'Delete Card?',
    deleteBody: 'This card has no linked transactions and will be permanently deleted.',
    deleteCancel: 'Cancel',
    deleteConfirm: 'Delete',
    negativeBalanceTitle: 'Balance Warning',
    negativeBalanceBody: 'Your credit card balance has gone below zero. Please check your transactions for accuracy.',
  },
  archiveModal: {
    title: 'Archive or Delete Card?',
    body: (count: number) =>
      `This card has ${count} linked transaction${count !== 1 ? 's' : ''}. Archiving hides the card everywhere but keeps your history intact.`,
    archiveButton: 'Archive Card',
    deleteAnywayButton: 'Delete Anyway',
  },
  logs: {
    createFailed: 'Failed to create credit card:',
    updateFailed: 'Failed to update credit card:',
    removeFailed: 'Failed to remove credit card:',
    archiveFailed: 'Failed to archive credit card:',
  },
  form: {
    addTitle: 'Add Credit Card',
    editTitle: 'Edit Credit Card',
    saveButton: 'Save Card',
    cancelButton: 'Cancel',
    addButton: 'Add Card',
    cancelEditButton: 'Cancel',
    labels: {
      nickname: 'Card Name',
      provider: 'Provider',
      bank: 'Bank',
      last4: 'Last 4 Digits',
      creditLimit: 'Credit Limit',
      statementDay: 'Statement Day',
      paymentBufferDays: 'Payment Buffer (days)',
    },
    placeholders: {
      nickname: 'e.g. Millennia',
      provider: 'Select Provider',
      bank: 'e.g. HDFC Bank',
      last4: '1234',
      creditLimit: 'e.g. 150000',
      statementDay: '1-31',
      paymentBufferDays: 'e.g. 15',
    },
  },
  providers: {
    visa: 'Visa',
    mastercard: 'Mastercard',
    amex: 'Amex',
    rupay: 'RuPay',
    diners: 'Diners',
    discover: 'Discover',
    other: 'Other',
  },
  validation: {
    required: 'This field is required',
    last4: 'Last 4 digits must be exactly 4 numbers',
    creditLimit: 'Credit limit must be greater than 0',
    statementDay: 'Statement day must be between 1 and 31',
    bufferDays: 'Payment buffer must be 0 or more',
  },
  preview: {
    nicknameFallback: 'Card Name',
    bankFallback: 'Bank',
    providerFallback: 'Provider',
    last4Fallback: '0000',
    mask: '**** **** ****',
    dueFallback: '--',
  },
  details: {
    screenTitle: 'Credit Card Details',
    loadingLabel: 'Loading card...',
    notFoundLabel: 'Card not found',
    amountDueLabel: 'Amount Due',
    carriedLabel: 'Carried',
    dueDateLabel: 'Due Date',
    usedLabel: 'Used',
    limitLabel: 'Limit',
    utilizationLabel: 'Utilization',
  },
  payBill: {
    title: 'Pay Bill',
    amountLabel: 'Payment Amount',
    amountPlaceholder: 'Enter amount',
    dateLabel: 'Payment Date',
    submitButton: 'Pay',
    cancelButton: 'Cancel',
    descriptionTemplate: (nickname: string) => `Bill paid for ${nickname}`,
    successTitle: 'Payment Recorded',
    successBody: (nickname: string, amount: string) => `₹${amount} payment for ${nickname} has been recorded.`,
    validation: {
      amountRequired: 'Amount must be greater than 0',
    },
    logs: {
      paymentFailed: 'Failed to record credit card payment:',
    },
  },
} as const;
