import { BCard, BIcon, BText, BView } from '@/src/components/ui';
import { CardVariant, Spacing, SpacingValue, TextVariant } from '@/src/constants/theme';
import { useThemeColors } from '@/src/hooks/theme-hooks/use-theme-color';
import { formatDate } from '@/src/utils/date';
import type { FC } from 'react';
import { StyleSheet } from 'react-native';

export interface TransactionCardProps {
  /** Expense/saving unique ID */
  id: string;
  /** Display description or fallback label */
  description: string | null;
  /** Amount in rupees */
  amount: number;
  /** Date string (YYYY-MM-DD) */
  date: string;
  /** Category name (null for one-off savings) */
  categoryName?: string | null;
  /** Ionicons icon name for category */
  categoryIcon?: string | null;
  /** Category hex color */
  categoryColor?: string | null;
  /** Savings type label (for one-off savings) */
  savingsType?: string | null;
  /** True if this is a saving (green), false = expense (red) */
  isSaving?: boolean;
  /** True if this was auto-generated by the recurring engine */
  isRecurring?: boolean;
  /** True if this expense was synced from Splitwise */
  isSplitwiseSynced?: boolean;
}

const TransactionCard: FC<TransactionCardProps> = ({
  description,
  amount,
  date,
  categoryName,
  categoryIcon,
  categoryColor,
  savingsType,
  isSaving = false,
  isSplitwiseSynced = false,
}) => {
  const themeColors = useThemeColors();

  const subtitle = categoryName ?? savingsType ?? '';
  const amountColor = isSaving ? themeColors.success : themeColors.error;
  const amountPrefix = isSaving ? '+' : '-';
  const iconName = categoryIcon ?? (isSaving ? 'wallet-outline' : 'cash-outline');
  const iconColor = categoryColor ?? (isSaving ? themeColors.success : themeColors.textMuted);
  const iconBg = categoryColor ? `${categoryColor}20` : themeColors.muted;

  return (
    <BCard variant={CardVariant.DEFAULT} style={styles.card}>
      <BView row justify="space-between" align="center">
        {/* Left: icon badge + text */}
        <BView row align="center" gap={SpacingValue.MD} flex>
          <BView center rounded="base" style={[styles.iconBadge, { backgroundColor: iconBg }]}>
            <BIcon name={iconName as any} size="sm" color={iconColor} />
          </BView>
          <BView flex>
            <BText variant={TextVariant.LABEL} numberOfLines={1}>
              {description || (isSaving ? 'Saving' : 'Expense')}
            </BText>
            <BText variant={TextVariant.CAPTION} muted>
              {formatDate(date)}
              {subtitle ? ` · ${subtitle}` : ''}
            </BText>
          </BView>
        </BView>
        {/* Right: amount + optional Splitwise badge */}
        <BView align="flex-end" gap={SpacingValue.XS}>
          <BText variant={TextVariant.LABEL} style={{ color: amountColor }}>
            {amountPrefix}₹{amount.toLocaleString('en-IN')}
          </BText>
          {isSplitwiseSynced && (
            <BView row align="center" gap={SpacingValue.XS} style={styles.splitwiseBadge}>
              <BIcon name="people-outline" size="xs" color="#1BAE83" />
              <BText variant={TextVariant.CAPTION} style={{ color: '#1BAE83', fontSize: 9 }}>
                Splitwise
              </BText>
            </BView>
          )}
        </BView>
      </BView>
    </BCard>
  );
};

const styles = StyleSheet.create({
  card: {
    padding: Spacing.md,
  },
  iconBadge: {
    width: 36,
    height: 36,
  },
  splitwiseBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: 'rgba(27, 174, 131, 0.12)',
  },
});

export default TransactionCard;
