import { BCard, BIcon, BText, BView } from '@/src/components/ui';
import { CardVariant, IconSize, SpacingValue, TextVariant } from '@/src/constants/theme';
import { SPLITWISE_STRINGS } from '@/src/constants/splitwise.strings';
import { TRANSACTION_CARD_STRINGS } from '@/src/constants/transactions.strings';
import { useThemeColors } from '@/src/hooks/theme-hooks/use-theme-color';
import { formatDate } from '@/src/utils/date';
import { formatCurrency } from '@/src/utils/format';
import type { FC } from 'react';

export interface TransactionCardProps {
  /** Expense/saving unique ID */
  id: string;
  /** Display description or fallback label */
  description: string | null;
  /** Amount in rupees */
  amount: number;
  /** Date string (YYYY-MM-DD) */
  date: string;
  /** Category name (null for one-off savings) */
  categoryName?: string | null;
  /** Ionicons icon name for category */
  categoryIcon?: string | null;
  /** Category hex color */
  categoryColor?: string | null;
  /** Savings type label (for one-off savings) */
  savingsType?: string | null;
  /** True if this is a saving (green), false = expense (red) */
  isSaving?: boolean;
  /** True if this was auto-generated by the recurring engine */
  isRecurring?: boolean;
  /** Card nickname for credit card attribution */
  creditCardNickname?: string | null;
  /** Card last 4 digits for credit card attribution */
  creditCardLast4?: string | null;
  /** Provider brand colour for the attribution dot */
  creditCardColor?: string | null;
  /** True if this is a credit card bill payment */
  isBillPay?: boolean;
  /** True if this expense was imported from Splitwise */
  isFromSplitwise?: boolean;
}

const TransactionCard: FC<TransactionCardProps> = ({
  description,
  amount,
  date,
  categoryName,
  categoryIcon,
  categoryColor,
  savingsType,
  isSaving = false,
  creditCardNickname,
  creditCardLast4,
  creditCardColor,
  isBillPay = false,
  isFromSplitwise = false,
}) => {
  const themeColors = useThemeColors();

  const subtitle = categoryName ?? savingsType ?? '';
  const amountColor = isSaving ? themeColors.success : themeColors.error;
  const amountPrefix = isSaving ? '+' : '-';
  const iconName = categoryIcon ?? (isSaving ? 'wallet-outline' : 'cash-outline');
  const iconColor = categoryColor ?? (isSaving ? themeColors.success : themeColors.textMuted);
  const iconBg = categoryColor ? `${categoryColor}20` : themeColors.muted;
  const hasCardAttribution = Boolean(creditCardNickname && creditCardLast4);

  return (
    <BCard variant={CardVariant.SUMMARY}>
      <BView row justify="space-between" align="center">
        {/* Left: icon badge + text */}
        <BView row align="center" gap={SpacingValue.MD} flex>
          <BView
            center
            rounded="base"
            style={{ width: IconSize['2xl'], height: IconSize['2xl'], backgroundColor: iconBg }}
          >
            <BIcon name={iconName as any} size="sm" color={iconColor} />
          </BView>
          <BView flex>
            {/* Title row: description + Bill Pay badge + Splitwise badge */}
            <BView row align="center" gap={SpacingValue.XS}>
              <BText variant={TextVariant.LABEL} numberOfLines={1} style={{ flexShrink: 1 }}>
                {description || (isSaving ? 'Saving' : 'Expense')}
              </BText>
              {isBillPay && (
                <BView
                  rounded={SpacingValue.XS}
                  bg={themeColors.primary}
                  paddingX={SpacingValue.SM}
                  paddingY={SpacingValue.XXS}
                >
                  <BText variant={TextVariant.CAPTION} color={themeColors.white}>
                    {TRANSACTION_CARD_STRINGS.billPayBadge}
                  </BText>
                </BView>
              )}
              {isFromSplitwise && (
                <BView
                  rounded={SpacingValue.XS}
                  bg={themeColors.success}
                  paddingX={SpacingValue.SM}
                  paddingY={SpacingValue.XXS}
                >
                  <BText variant={TextVariant.CAPTION} color={themeColors.white}>
                    {SPLITWISE_STRINGS.transactionBadge}
                  </BText>
                </BView>
              )}
            </BView>
            {/* Subtitle row: date · category [· dot cardname ••last4] */}
            <BView row align="center" gap={SpacingValue.XS} style={{ flexWrap: 'wrap' }}>
              <BText variant={TextVariant.CAPTION} muted>
                {formatDate(date)}
                {subtitle ? `${TRANSACTION_CARD_STRINGS.cardSeparator}${subtitle}` : ''}
              </BText>
              {hasCardAttribution && (
                <>
                  <BView fullRounded bg={creditCardColor ?? themeColors.primary} style={{ width: 6, height: 6 }} />
                  <BText variant={TextVariant.CAPTION} muted>
                    {creditCardNickname} {TRANSACTION_CARD_STRINGS.cardMask}
                    {creditCardLast4}
                  </BText>
                </>
              )}
            </BView>
          </BView>
        </BView>
        {/* Right: amount */}
        <BText style={{ color: amountColor }}>
          {amountPrefix}
          {formatCurrency(amount)}
        </BText>
      </BView>
    </BCard>
  );
};

export default TransactionCard;
